// Typed wrapper around the 33-season stats pack generated by
// backend/scripts/compute_stats_pack.py. Ships with the bundle — no runtime
// HTTP, no backend dependency at inference.
//
// The CSV dataset canonicalises team names without the "FC" suffix
// (e.g. "Arsenal", "Man City"). The frontend receives API names from
// Football-Data.org that include the suffix ("Arsenal FC", "Manchester City
// FC"). API_TO_CSV_ALIAS below translates the one into the other so consumers
// can look up stats with whichever name they have.

import rawStatsPack from './statsPack.json';

export interface HalfTimeTempo {
  matches: number;
  avgFirstHalfGoalsScored: number;
  avgSecondHalfGoalsScored: number;
  firstHalfShare: number; // proportion of total goals scored in the first half
  comebackWinRate: number; // rate of wins despite trailing at HT
  capitulationLossRate: number; // rate of losses despite leading at HT
}

export interface TeamProfile {
  totalMatches: number;
  homeGoalsScored: number;
  homeGoalsConceded: number;
  awayGoalsScored: number;
  awayGoalsConceded: number;
  cleanSheetRateHome: number;
  cleanSheetRateAway: number;
  failedToScoreRateHome: number;
  failedToScoreRateAway: number;
  over25Rate: number;
  bttsRate: number;
  recentScoringTrend: number;
  eraWeighted: {
    homeGoalsScored: number;
    homeGoalsConceded: number;
    awayGoalsScored: number;
    awayGoalsConceded: number;
  };
  // Optional — absent for pre-1995 teams whose CSVs lack HT goal columns
  halfTime?: HalfTimeTempo;
}

export interface SeasonStats {
  matches: number;
  homeWinRate: number;
  drawRate: number;
  awayWinRate: number;
  avgHomeGoals: number;
  avgAwayGoals: number;
  avgTotalGoals: number;
  over25Rate: number;
  bttsRate: number;
  isAnomalous: boolean;
  anomalyReasons: string[];
}

export interface Anomaly {
  season: string; // e.g. "2020/21"
  reasons: string[];
}

export interface RefereeStats {
  matches: number;
  avgGoalsPerMatch: number;
  goalsVsLeagueAvg: number; // + above / - below the league mean
  homeWinRate: number;
  drawRate: number;
  awayWinRate: number;
  over25Rate: number;
  bttsRate: number;
}

export interface PairStats {
  totalMatches: number;
  homeWins: number;
  draws: number;
  awayWins: number;
  avgHomeGoals: number;
  avgAwayGoals: number;
  avgTotalGoals: number;
  over25Rate: number;
  over35Rate: number;
  bttsRate: number;
  recentTenAvgTotal: number;
  historicalVariance: number;
}

export interface LeagueEra {
  avgHomeGoalsOverall: number;
  avgAwayGoalsOverall: number;
  avgTotalGoalsOverall: number;
  avgOver25Overall: number;
  avgBTTSOverall: number;
  avgHomeGoalsByDecade: Record<string, number>;
  avgHomeGoalsByMonth: Record<string, number>;
}

export interface StatsPack {
  generatedAt: string;
  eraDecay: number;
  referenceYear: number;
  totalMatches: number;
  totalSeasons: number;
  seasons: string[];
  leagueEra: LeagueEra;
  /**
   * Per-season aggregates keyed by season string ("2020/21"). Each entry
   * includes headline rates and an `isAnomalous` flag that fires when any
   * rate deviates >2 stdevs from the 33-season mean.
   */
  seasonStats: Record<string, SeasonStats>;
  /**
   * Pre-extracted list of seasons that `seasonStats` flagged as anomalous —
   * the 2020/21 COVID empty-stadium shift shows up here, for example. Useful
   * for surfacing contextual UI notes without iterating seasonStats.
   */
  anomalies: Anomaly[];
  /**
   * Per-referee goal tendency (only referees with >=50 PL matches retained).
   * Uses CSV referee names as keys; absent in very old CSVs.
   */
  referees: Record<string, RefereeStats>;
  teams: Record<string, TeamProfile>;
  pairs: Record<string, PairStats>;
}

export const statsPack = rawStatsPack as unknown as StatsPack;

// Map Football-Data.org API team names → CSV canonical names.
// Entries only needed where the two differ. Missing entries fall back to the
// raw API name (which will miss the lookup and return undefined — safe).
// Covers all 20 current 2025/26 PL teams plus a few common historical sides.
export const API_TO_CSV_ALIAS: Record<string, string> = {
  'Arsenal FC': 'Arsenal',
  'Aston Villa FC': 'Aston Villa',
  'AFC Bournemouth': 'Bournemouth',
  'Brentford FC': 'Brentford',
  'Brighton & Hove Albion FC': 'Brighton',
  'Burnley FC': 'Burnley',
  'Chelsea FC': 'Chelsea',
  'Crystal Palace FC': 'Crystal Palace',
  'Everton FC': 'Everton',
  'Fulham FC': 'Fulham',
  'Leeds United FC': 'Leeds',
  'Liverpool FC': 'Liverpool',
  'Manchester City FC': 'Man City',
  'Manchester United FC': 'Man United',
  'Newcastle United FC': 'Newcastle',
  'Nottingham Forest FC': "Nott'm Forest",
  'Sunderland AFC': 'Sunderland',
  'Tottenham Hotspur FC': 'Tottenham',
  'West Ham United FC': 'West Ham',
  'Wolverhampton Wanderers FC': 'Wolves',
  // Historical (promoted/relegated) — handy when showing legacy fixtures
  'Leicester City FC': 'Leicester',
  'Southampton FC': 'Southampton',
  'Ipswich Town FC': 'Ipswich',
  'Luton Town FC': 'Luton',
  'Sheffield United FC': 'Sheffield United',
};

/**
 * Resolve whichever form of a team name the caller has to the CSV canonical
 * form used as a key in the stats pack. If the name is already canonical
 * (not in the alias map), returned unchanged.
 */
export function canonicalTeam(name: string): string {
  return API_TO_CSV_ALIAS[name] ?? name;
}

/**
 * Look up a team's all-season profile. Returns undefined if the team never
 * appeared in the 33-season dataset (e.g. a freshly scraped or misspelled
 * name), in which case consumers should fall back to current-form signal.
 */
export function getTeamProfile(name: string): TeamProfile | undefined {
  return statsPack.teams[canonicalTeam(name)];
}

/**
 * Look up stats for an ordered (home, away) pair. Pair direction matters —
 * Arsenal home vs Chelsea is a different fixture than Chelsea home vs Arsenal.
 * Returns undefined if the pair has never met in the 33-season record (e.g.
 * newly promoted teams meeting for the first time ever).
 */
export function getPairStats(home: string, away: string): PairStats | undefined {
  return statsPack.pairs[`${canonicalTeam(home)}|${canonicalTeam(away)}`];
}

/**
 * League-era averages. The returned object is a direct reference to the pack
 * — do not mutate.
 */
export function getLeagueEra(): LeagueEra {
  return statsPack.leagueEra;
}

/**
 * Per-season aggregates for a given season string (e.g. "2020/21"), or
 * undefined if the season is not in the 33-season archive.
 */
export function getSeasonStats(season: string): SeasonStats | undefined {
  return statsPack.seasonStats?.[season];
}

/**
 * All seasons flagged as anomalous (e.g. COVID 2020/21 shift). Returns an
 * empty array if the pack was generated before the anomaly-detection
 * features were added.
 */
export function getAnomalies(): Anomaly[] {
  return statsPack.anomalies ?? [];
}

/**
 * Per-referee goal tendency. Accepts the CSV canonical referee name (e.g.
 * "M Oliver"). Returns undefined if the referee has <50 matches or the
 * pack's referees section is absent (very old CSVs).
 */
export function getRefereeStats(refereeName: string): RefereeStats | undefined {
  return statsPack.referees?.[refereeName];
}
