// Typed wrapper around the 33-season stats pack generated by
// backend/scripts/compute_stats_pack.py. Ships with the bundle — no runtime
// HTTP, no backend dependency at inference.
//
// The CSV dataset canonicalises team names without the "FC" suffix
// (e.g. "Arsenal", "Man City"). The frontend receives API names from
// Football-Data.org that include the suffix ("Arsenal FC", "Manchester City
// FC"). API_TO_CSV_ALIAS below translates the one into the other so consumers
// can look up stats with whichever name they have.

import rawStatsPack from './statsPack.json';

export interface TeamProfile {
  totalMatches: number;
  homeGoalsScored: number;
  homeGoalsConceded: number;
  awayGoalsScored: number;
  awayGoalsConceded: number;
  cleanSheetRateHome: number;
  cleanSheetRateAway: number;
  failedToScoreRateHome: number;
  failedToScoreRateAway: number;
  over25Rate: number;
  bttsRate: number;
  recentScoringTrend: number;
  eraWeighted: {
    homeGoalsScored: number;
    homeGoalsConceded: number;
    awayGoalsScored: number;
    awayGoalsConceded: number;
  };
}

export interface PairStats {
  totalMatches: number;
  homeWins: number;
  draws: number;
  awayWins: number;
  avgHomeGoals: number;
  avgAwayGoals: number;
  avgTotalGoals: number;
  over25Rate: number;
  over35Rate: number;
  bttsRate: number;
  recentTenAvgTotal: number;
  historicalVariance: number;
}

export interface LeagueEra {
  avgHomeGoalsOverall: number;
  avgAwayGoalsOverall: number;
  avgTotalGoalsOverall: number;
  avgOver25Overall: number;
  avgBTTSOverall: number;
  avgHomeGoalsByDecade: Record<string, number>;
  avgHomeGoalsByMonth: Record<string, number>;
}

export interface StatsPack {
  generatedAt: string;
  eraDecay: number;
  referenceYear: number;
  totalMatches: number;
  totalSeasons: number;
  seasons: string[];
  leagueEra: LeagueEra;
  teams: Record<string, TeamProfile>;
  pairs: Record<string, PairStats>;
}

export const statsPack = rawStatsPack as unknown as StatsPack;

// Map Football-Data.org API team names → CSV canonical names.
// Entries only needed where the two differ. Missing entries fall back to the
// raw API name (which will miss the lookup and return undefined — safe).
// Covers all 20 current 2025/26 PL teams plus a few common historical sides.
export const API_TO_CSV_ALIAS: Record<string, string> = {
  'Arsenal FC': 'Arsenal',
  'Aston Villa FC': 'Aston Villa',
  'AFC Bournemouth': 'Bournemouth',
  'Brentford FC': 'Brentford',
  'Brighton & Hove Albion FC': 'Brighton',
  'Burnley FC': 'Burnley',
  'Chelsea FC': 'Chelsea',
  'Crystal Palace FC': 'Crystal Palace',
  'Everton FC': 'Everton',
  'Fulham FC': 'Fulham',
  'Leeds United FC': 'Leeds',
  'Liverpool FC': 'Liverpool',
  'Manchester City FC': 'Man City',
  'Manchester United FC': 'Man United',
  'Newcastle United FC': 'Newcastle',
  'Nottingham Forest FC': "Nott'm Forest",
  'Sunderland AFC': 'Sunderland',
  'Tottenham Hotspur FC': 'Tottenham',
  'West Ham United FC': 'West Ham',
  'Wolverhampton Wanderers FC': 'Wolves',
  // Historical (promoted/relegated) — handy when showing legacy fixtures
  'Leicester City FC': 'Leicester',
  'Southampton FC': 'Southampton',
  'Ipswich Town FC': 'Ipswich',
  'Luton Town FC': 'Luton',
  'Sheffield United FC': 'Sheffield United',
};

/**
 * Resolve whichever form of a team name the caller has to the CSV canonical
 * form used as a key in the stats pack. If the name is already canonical
 * (not in the alias map), returned unchanged.
 */
export function canonicalTeam(name: string): string {
  return API_TO_CSV_ALIAS[name] ?? name;
}

/**
 * Look up a team's all-season profile. Returns undefined if the team never
 * appeared in the 33-season dataset (e.g. a freshly scraped or misspelled
 * name), in which case consumers should fall back to current-form signal.
 */
export function getTeamProfile(name: string): TeamProfile | undefined {
  return statsPack.teams[canonicalTeam(name)];
}

/**
 * Look up stats for an ordered (home, away) pair. Pair direction matters —
 * Arsenal home vs Chelsea is a different fixture than Chelsea home vs Arsenal.
 * Returns undefined if the pair has never met in the 33-season record (e.g.
 * newly promoted teams meeting for the first time ever).
 */
export function getPairStats(home: string, away: string): PairStats | undefined {
  return statsPack.pairs[`${canonicalTeam(home)}|${canonicalTeam(away)}`];
}

/**
 * League-era averages. The returned object is a direct reference to the pack
 * — do not mutate.
 */
export function getLeagueEra(): LeagueEra {
  return statsPack.leagueEra;
}
