// Typed wrapper around the 33-season stats pack generated by
// backend/scripts/compute_stats_pack.py. Ships with the bundle — no runtime
// HTTP, no backend dependency at inference.
//
// The CSV dataset canonicalises team names without the "FC" suffix
// (e.g. "Arsenal", "Man City"). The frontend receives API names from
// Football-Data.org that include the suffix ("Arsenal FC", "Manchester City
// FC"). API_TO_CSV_ALIAS below translates the one into the other so consumers
// can look up stats with whichever name they have.

import rawStatsPack from './statsPack.json';

export interface HalfTimeTempo {
  matches: number;
  avgFirstHalfGoalsScored: number;
  avgSecondHalfGoalsScored: number;
  firstHalfShare: number; // proportion of total goals scored in the first half
  comebackWinRate: number; // rate of wins despite trailing at HT
  capitulationLossRate: number; // rate of losses despite leading at HT
  // Rare: rescues from ≥2 goals down at HT to at least a draw at FT.
  comebacksFromTwoDownRate?: number;
  comebacksFromTwoDownCount?: number;
}

/**
 * Goal-frequency tail for one venue (home or away). The `distribution` field
 * is a histogram keyed "0".."5" plus "6+", summing to ~1.0. Use these rates
 * as direct observations of P(score ≥ N) rather than relying on Poisson CDF
 * estimates at fitted λ — top teams hit the tail meaningfully more often than
 * their mean λ would imply.
 */
export interface GoalFrequencyVenue {
  scored3Plus: number;
  scored4Plus: number;
  scored5Plus: number;
  scored6Plus: number;
  conceded3Plus: number;
  conceded4Plus: number;
  distribution: Record<string, number>;
}

export interface GoalFrequencyEraWeighted {
  homeScored3Plus: number;
  homeScored4Plus: number;
  homeScored5Plus: number;
  awayScored3Plus: number;
  awayScored4Plus: number;
  awayScored5Plus: number;
}

export interface GoalFrequency {
  home: GoalFrequencyVenue;
  away: GoalFrequencyVenue;
  eraWeighted: GoalFrequencyEraWeighted;
}

/**
 * Big-win / capitulation margins. `homeBy3Plus` = the team won at home by 3+
 * goals; `homeLossBy3Plus` = the team lost at home by 3+ goals. Useful for
 * reasoning about blowout probability on either side of the predicted result.
 */
export interface BigWin {
  homeBy3Plus: number;
  awayBy3Plus: number;
  homeLossBy3Plus: number;
  awayLossBy3Plus: number;
}

/**
 * Longest consecutive runs in the 33-season archive. Scoring-run = fixtures
 * where the team scored at least 1 goal; clean-sheet = the team kept the
 * opposition to 0. Informative but not directly consumed by the ensemble.
 */
export interface Streaks {
  longestScoringRunHome: number;
  longestScoringRunAway: number;
  longestCleanSheetRunHome: number;
  longestCleanSheetRunAway: number;
  longestWinRun?: number;
  longestLosingRun?: number;
  longestWinlessRun?: number;
}

/**
 * Performance split vs a tier of opposition — the single strongest signal
 * for "big teams score 3+ against weak teams" that the aggregated goal
 * average blurs. `scored3PlusRate` vs bottom-6 opponents captures blowout
 * potential directly; compare against `leagueGoalFrequency.homeScored3PlusRate`
 * for exceptionality.
 */
export interface OppositionTierStats {
  matches: number;
  avgGoalsScored: number;
  avgGoalsConceded: number;
  winRate: number;
  scored3PlusRate: number;
}

export interface OppositionTierBlock {
  top6?: OppositionTierStats; // opponent finished 1-6 in that season
  mid?: OppositionTierStats; // opponent finished 7-14
  bottom6?: OppositionTierStats; // opponent finished 15-20
}

/**
 * Shot-to-goal conversion where the underlying CSV carries shot columns
 * (post-2000 for most teams). Captures clinical finishing vs wasteful
 * possession sides.
 */
export interface ShotEfficiencyVenue {
  matches: number;
  avgShotsFor: number;
  avgShotsOnTargetFor?: number;
  goalsPerShot: number;
  goalsPerShotOnTarget?: number;
}

export interface ShotEfficiency {
  home?: ShotEfficiencyVenue;
  away?: ShotEfficiencyVenue;
}

/**
 * Biggest-margin historical fixture scores for a pair. Use for UI context
 * like "Arsenal's biggest home win over Burnley: 5-0 in 2017/18".
 */
export interface BiggestMargin {
  score: string; // home-goals-first, e.g. "5-0"
  margin: number;
  season: string | null;
}

export interface BiggestMargins {
  biggestHomeWin?: BiggestMargin;
  biggestAwayWin?: BiggestMargin;
}

export interface LeagueGoalFrequency {
  homeScored3PlusRate: number;
  homeScored4PlusRate: number;
  homeScored5PlusRate: number;
  awayScored3PlusRate: number;
  awayScored4PlusRate: number;
  awayScored5PlusRate: number;
  match3PlusGoalsEitherRate: number; // either side scored ≥3
  match4PlusGoalsEitherRate: number; // either side scored ≥4
  match5PlusTotalRate: number; // total goals ≥5
  match6PlusTotalRate: number; // total goals ≥6
  highestScoringMatch: number; // largest single-match total goals in the archive
}

export interface OverRates {
  over15: number;
  over25: number;
  over35: number;
  over45: number;
  under15: number;
  under25: number;
}

export interface HomeAdvantage {
  homeWinRate: number;
  awayWinRate: number;
  homeAwayWinDelta: number; // home win rate − away win rate
  homeAwayGoalsScoredDelta: number; // home avg scored − away avg scored
  homeAwayGoalsConcededDelta: number; // home avg conceded − away avg conceded
}

export interface CommonScoreline {
  score: string; // home-goals-first notation, e.g. "2-1"
  count: number;
  rate: number;
}

export interface CommonScorelines {
  atHome?: CommonScoreline[]; // top-3 when team plays at home, ≥20 matches
  awayFrom?: CommonScoreline[]; // top-3 when team plays away, ≥20 matches
}

export interface TeamProfile {
  totalMatches: number;
  homeGoalsScored: number;
  homeGoalsConceded: number;
  awayGoalsScored: number;
  awayGoalsConceded: number;
  cleanSheetRateHome: number;
  cleanSheetRateAway: number;
  failedToScoreRateHome: number;
  failedToScoreRateAway: number;
  over25Rate: number;
  bttsRate: number;
  recentScoringTrend: number;
  // Population variance of goals scored per match across all appearances —
  // high = swingy team, low = consistent scorer.
  goalVariance: number;
  // Rates of total match goals crossing over/under thresholds across all
  // appearances (home + away pooled).
  overRates: OverRates;
  eraWeighted: {
    homeGoalsScored: number;
    homeGoalsConceded: number;
    awayGoalsScored: number;
    awayGoalsConceded: number;
  };
  // Optional — absent for pre-1995 teams whose CSVs lack HT goal columns
  halfTime?: HalfTimeTempo;
  // Optional — absent when the team has no fixtures on one side of the venue
  // split (e.g. recently promoted sides with <1 season of PL data).
  homeAdvantage?: HomeAdvantage;
  // Optional — generator skips a side of the split with <20 matches, and
  // omits the whole field if both sides are too thin.
  commonScorelines?: CommonScorelines;
  // Goal-frequency tail data. Direct observations of P(score ≥ N) per venue,
  // plus histogram and era-weighted thresholds for current-relevance bias.
  goalFrequency?: GoalFrequency;
  // Big-win + big-loss margins.
  bigWin?: BigWin;
  // Longest consecutive scoring / clean-sheet runs on each side of the venue.
  streaks?: Streaks;
  // Performance splits vs top-6 / mid / bottom-6 opposition (opponent's FINAL
  // position in the same season). Primary signal for "favourite crushes
  // underdog" lambda lifts.
  oppositionTier?: OppositionTierBlock;
  // Shot-to-goal conversion per venue, where CSV shot columns were populated
  // (post-2000 era for most teams).
  shotEfficiency?: ShotEfficiency;
}

export interface SeasonStats {
  matches: number;
  homeWinRate: number;
  drawRate: number;
  awayWinRate: number;
  avgHomeGoals: number;
  avgAwayGoals: number;
  avgTotalGoals: number;
  over25Rate: number;
  bttsRate: number;
  isAnomalous: boolean;
  anomalyReasons: string[];
}

export interface Anomaly {
  season: string; // e.g. "2020/21"
  reasons: string[];
}

export interface RefereeStats {
  matches: number;
  avgGoalsPerMatch: number;
  goalsVsLeagueAvg: number; // + above / - below the league mean
  homeWinRate: number;
  drawRate: number;
  awayWinRate: number;
  over25Rate: number;
  bttsRate: number;
  // Discipline / set-piece averages — only populated where the CSV supplies
  // the columns and they aren't all NaN (older seasons may omit any of them).
  avgYellowsPerMatch?: number;
  avgRedsPerMatch?: number;
  avgFoulsPerMatch?: number;
  avgCornersPerMatch?: number;
}

/**
 * 9-key HT × FT outcome matrix. Keys are `<HT><FT>` where each outcome letter
 * is H (home), D (draw) or A (away). Populated only when the pair has ≥5
 * meetings with half-time data available — undefined otherwise.
 */
export interface HtFtMatrix {
  HH: number;
  HD: number;
  HA: number;
  DH: number;
  DD: number;
  DA: number;
  AH: number;
  AD: number;
  AA: number;
}

export interface PairStats {
  totalMatches: number;
  homeWins: number;
  draws: number;
  awayWins: number;
  avgHomeGoals: number;
  avgAwayGoals: number;
  avgTotalGoals: number;
  over25Rate: number;
  over35Rate: number;
  bttsRate: number;
  recentTenAvgTotal: number;
  historicalVariance: number;
  // True when the (home, away) pair is one of the hardcoded derby fixtures
  // in the generator (both direction orderings count — see DERBY_PAIRS in
  // backend/scripts/compute_stats_pack.py).
  isDerby: boolean;
  // Optional — generator omits when the pair has <5 meetings with HT data.
  htFtMatrix?: HtFtMatrix;
  // Biggest recorded home / away win margin in the fixture's 33-season
  // history. Useful for UI context and establishing the historical ceiling.
  biggestMargins?: BiggestMargins;
}

export interface MatchdayStats {
  matches: number;
  avgTotalGoals: number;
  homeWinRate: number;
  drawRate: number;
  awayWinRate: number;
  over25Rate: number;
}

export interface LeagueEra {
  avgHomeGoalsOverall: number;
  avgAwayGoalsOverall: number;
  avgTotalGoalsOverall: number;
  avgOver25Overall: number;
  avgBTTSOverall: number;
  avgHomeGoalsByDecade: Record<string, number>;
  avgHomeGoalsByMonth: Record<string, number>;
}

export interface StatsPack {
  generatedAt: string;
  eraDecay: number;
  referenceYear: number;
  totalMatches: number;
  totalSeasons: number;
  seasons: string[];
  leagueEra: LeagueEra;
  /**
   * Per-season aggregates keyed by season string ("2020/21"). Each entry
   * includes headline rates and an `isAnomalous` flag that fires when any
   * rate deviates >2 stdevs from the 33-season mean.
   */
  seasonStats: Record<string, SeasonStats>;
  /**
   * Pre-extracted list of seasons that `seasonStats` flagged as anomalous —
   * the 2020/21 COVID empty-stadium shift shows up here, for example. Useful
   * for surfacing contextual UI notes without iterating seasonStats.
   */
  anomalies: Anomaly[];
  /**
   * Per-referee goal tendency (only referees with >=50 PL matches retained).
   * Uses CSV referee names as keys; absent in very old CSVs.
   */
  referees: Record<string, RefereeStats>;
  teams: Record<string, TeamProfile>;
  pairs: Record<string, PairStats>;
  /**
   * Per-matchday league aggregates keyed by matchday number as a string
   * ("1".."38"). Matchday is inferred as the Nth chronological league match
   * each team plays within a season — for the rare rescheduled fixture where
   * the two clubs' counts diverge, the fixture takes the higher ordinal.
   * Optional because older generator runs may predate this section.
   */
  matchdayStats?: Record<string, MatchdayStats>;
  /**
   * League-wide high-scoring normaliser. Useful when reasoning about whether
   * a team's 3+/4+/5+ rate is exceptional — comparing the team's rate against
   * these league-average numerators is the direct way to identify blowout
   * teams (Man City's home 3+ rate 0.37 vs league 0.20 = 1.8× more likely).
   */
  leagueGoalFrequency?: LeagueGoalFrequency;
}

export const statsPack = rawStatsPack as unknown as StatsPack;

// Map Football-Data.org API team names → CSV canonical names.
// Entries only needed where the two differ. Missing entries fall back to the
// raw API name (which will miss the lookup and return undefined — safe).
// Covers all 20 current 2025/26 PL teams plus a few common historical sides.
export const API_TO_CSV_ALIAS: Record<string, string> = {
  'Arsenal FC': 'Arsenal',
  'Aston Villa FC': 'Aston Villa',
  'AFC Bournemouth': 'Bournemouth',
  'Brentford FC': 'Brentford',
  'Brighton & Hove Albion FC': 'Brighton',
  'Burnley FC': 'Burnley',
  'Chelsea FC': 'Chelsea',
  'Crystal Palace FC': 'Crystal Palace',
  'Everton FC': 'Everton',
  'Fulham FC': 'Fulham',
  'Leeds United FC': 'Leeds',
  'Liverpool FC': 'Liverpool',
  'Manchester City FC': 'Man City',
  'Manchester United FC': 'Man United',
  'Newcastle United FC': 'Newcastle',
  'Nottingham Forest FC': "Nott'm Forest",
  'Sunderland AFC': 'Sunderland',
  'Tottenham Hotspur FC': 'Tottenham',
  'West Ham United FC': 'West Ham',
  'Wolverhampton Wanderers FC': 'Wolves',
  // Historical (promoted/relegated) — handy when showing legacy fixtures
  'Leicester City FC': 'Leicester',
  'Southampton FC': 'Southampton',
  'Ipswich Town FC': 'Ipswich',
  'Luton Town FC': 'Luton',
  'Sheffield United FC': 'Sheffield United',
};

/**
 * Resolve whichever form of a team name the caller has to the CSV canonical
 * form used as a key in the stats pack. If the name is already canonical
 * (not in the alias map), returned unchanged.
 */
export function canonicalTeam(name: string): string {
  return API_TO_CSV_ALIAS[name] ?? name;
}

/**
 * Look up a team's all-season profile. Returns undefined if the team never
 * appeared in the 33-season dataset (e.g. a freshly scraped or misspelled
 * name), in which case consumers should fall back to current-form signal.
 */
export function getTeamProfile(name: string): TeamProfile | undefined {
  return statsPack.teams[canonicalTeam(name)];
}

/**
 * Look up stats for an ordered (home, away) pair. Pair direction matters —
 * Arsenal home vs Chelsea is a different fixture than Chelsea home vs Arsenal.
 * Returns undefined if the pair has never met in the 33-season record (e.g.
 * newly promoted teams meeting for the first time ever).
 */
export function getPairStats(home: string, away: string): PairStats | undefined {
  return statsPack.pairs[`${canonicalTeam(home)}|${canonicalTeam(away)}`];
}

/**
 * League-era averages. The returned object is a direct reference to the pack
 * — do not mutate.
 */
export function getLeagueEra(): LeagueEra {
  return statsPack.leagueEra;
}

/**
 * Per-season aggregates for a given season string (e.g. "2020/21"), or
 * undefined if the season is not in the 33-season archive.
 */
export function getSeasonStats(season: string): SeasonStats | undefined {
  return statsPack.seasonStats?.[season];
}

/**
 * All seasons flagged as anomalous (e.g. COVID 2020/21 shift). Returns an
 * empty array if the pack was generated before the anomaly-detection
 * features were added.
 */
export function getAnomalies(): Anomaly[] {
  return statsPack.anomalies ?? [];
}

/**
 * Per-referee goal tendency. Accepts the CSV canonical referee name (e.g.
 * "M Oliver"). Returns undefined if the referee has <50 matches or the
 * pack's referees section is absent (very old CSVs).
 */
export function getRefereeStats(refereeName: string): RefereeStats | undefined {
  return statsPack.referees?.[refereeName];
}

/**
 * League-wide goal-frequency summary — home/away scored-≥N rates, match-level
 * blowout rates, and the highest-scoring match in the archive. Useful as a
 * normaliser for team-level goal-frequency exceptionality checks.
 */
export function getLeagueGoalFrequency(): LeagueGoalFrequency | undefined {
  return statsPack.leagueGoalFrequency;
}

/**
 * League aggregates for a given matchday (1-38). Returns undefined if the
 * matchday is out of range or the pack predates the matchdayStats section.
 */
export function getMatchdayStats(matchday: number): MatchdayStats | undefined {
  if (!Number.isFinite(matchday) || matchday < 1 || matchday > 38) return undefined;
  return statsPack.matchdayStats?.[String(Math.trunc(matchday))];
}
