/**
 * Demo data for screenshot / preview mode.
 * Activated via `?demo=1`, `localStorage.kicker:demoMode === 'on'`, or `VITE_DEMO_MODE`.
 * Never shown when a Football-Data API key is configured for the real user.
 */

import type { Match } from '../../types/index.js';

export const DEMO_MATCHES: Match[] = [
  // ── Gameweek 35 completed fixtures (Sat 23 May 2026) ──────────────────────

  {
    id: 'demo-match-1',
    season_id: '2025-26',
    date: '2026-05-23T15:00:00+01:00',
    home_team: 'Manchester City FC',
    away_team: 'Aston Villa FC',
    home_goals: 3,
    away_goals: 1,
    result: 'H',
    home_odds: 1.65,
    draw_odds: 4.00,
    away_odds: 5.50,
    first_half_home_goals: 2,
    first_half_away_goals: 0,
    full_time_result: 'H',
    half_time_result: 'H',
    referee: 'Michael Oliver',
    home_shots: 18,
    away_shots: 8,
    home_shots_target: 7,
    away_shots_target: 3,
    home_fouls: 10,
    away_fouls: 14,
    home_corners: 8,
    away_corners: 3,
    home_yellows: 1,
    away_yellows: 3,
    home_reds: 0,
    away_reds: 0,
    created_at: '2026-05-01T00:00:00Z',
    status: 'FINISHED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-2',
    season_id: '2025-26',
    date: '2026-05-23T15:00:00+01:00',
    home_team: 'Liverpool FC',
    away_team: 'Tottenham Hotspur FC',
    home_goals: 2,
    away_goals: 2,
    result: 'D',
    home_odds: 1.75,
    draw_odds: 3.80,
    away_odds: 4.80,
    first_half_home_goals: 1,
    first_half_away_goals: 1,
    full_time_result: 'D',
    half_time_result: 'D',
    referee: 'Anthony Taylor',
    home_shots: 15,
    away_shots: 12,
    home_shots_target: 5,
    away_shots_target: 4,
    home_fouls: 9,
    away_fouls: 11,
    home_corners: 7,
    away_corners: 5,
    home_yellows: 2,
    away_yellows: 2,
    home_reds: 0,
    away_reds: 0,
    created_at: '2026-05-01T00:00:00Z',
    status: 'FINISHED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-3',
    season_id: '2025-26',
    date: '2026-05-23T17:30:00+01:00',
    home_team: 'Arsenal FC',
    away_team: 'Chelsea FC',
    home_goals: 1,
    away_goals: 0,
    result: 'H',
    home_odds: 2.00,
    draw_odds: 3.50,
    away_odds: 3.80,
    first_half_home_goals: 0,
    first_half_away_goals: 0,
    full_time_result: 'H',
    half_time_result: 'D',
    referee: 'Stuart Attwell',
    home_shots: 14,
    away_shots: 10,
    home_shots_target: 4,
    away_shots_target: 2,
    home_fouls: 12,
    away_fouls: 13,
    home_corners: 6,
    away_corners: 4,
    home_yellows: 1,
    away_yellows: 3,
    home_reds: 0,
    away_reds: 1,
    created_at: '2026-05-01T00:00:00Z',
    status: 'FINISHED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-4',
    season_id: '2025-26',
    date: '2026-05-23T17:30:00+01:00',
    home_team: 'Nottingham Forest FC',
    away_team: 'Manchester United FC',
    home_goals: 0,
    away_goals: 2,
    result: 'A',
    home_odds: 2.70,
    draw_odds: 3.40,
    away_odds: 2.60,
    first_half_home_goals: 0,
    first_half_away_goals: 1,
    full_time_result: 'A',
    half_time_result: 'A',
    referee: 'Paul Tierney',
    home_shots: 9,
    away_shots: 13,
    home_shots_target: 2,
    away_shots_target: 5,
    home_fouls: 15,
    away_fouls: 8,
    home_corners: 4,
    away_corners: 7,
    home_yellows: 3,
    away_yellows: 1,
    home_reds: 0,
    away_reds: 0,
    created_at: '2026-05-01T00:00:00Z',
    status: 'FINISHED',
    minute: null,
    matchday: 35,
  },

  // ── Live match (Sun 24 May 2026, 67 min) ──────────────────────────────────

  {
    id: 'demo-match-5',
    season_id: '2025-26',
    date: '2026-05-24T15:00:00+01:00',
    home_team: 'Newcastle United FC',
    away_team: 'Brighton & Hove Albion FC',
    home_goals: 1,
    away_goals: 2,
    result: null,
    home_odds: 2.10,
    draw_odds: 3.50,
    away_odds: 3.40,
    first_half_home_goals: 1,
    first_half_away_goals: 1,
    full_time_result: null,
    half_time_result: 'D',
    referee: 'Chris Kavanagh',
    home_shots: 9,
    away_shots: 11,
    home_shots_target: 3,
    away_shots_target: 5,
    home_fouls: 7,
    away_fouls: 9,
    home_corners: 4,
    away_corners: 6,
    home_yellows: 1,
    away_yellows: 2,
    home_reds: 0,
    away_reds: 0,
    created_at: '2026-05-01T00:00:00Z',
    status: 'IN_PLAY',
    minute: 67,
    matchday: 35,
  },

  // ── Upcoming fixtures (weekend of 30-31 May 2026) ─────────────────────────

  {
    id: 'demo-match-6',
    season_id: '2025-26',
    date: '2026-05-30T15:00:00+01:00',
    home_team: 'Manchester City FC',
    away_team: 'Liverpool FC',
    home_goals: null,
    away_goals: null,
    result: null,
    home_odds: 2.30,
    draw_odds: 3.50,
    away_odds: 3.10,
    first_half_home_goals: null,
    first_half_away_goals: null,
    full_time_result: null,
    half_time_result: null,
    referee: null,
    home_shots: null,
    away_shots: null,
    home_shots_target: null,
    away_shots_target: null,
    home_fouls: null,
    away_fouls: null,
    home_corners: null,
    away_corners: null,
    home_yellows: null,
    away_yellows: null,
    home_reds: null,
    away_reds: null,
    created_at: '2026-05-01T00:00:00Z',
    status: 'TIMED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-7',
    season_id: '2025-26',
    date: '2026-05-30T17:30:00+01:00',
    home_team: 'Arsenal FC',
    away_team: 'Newcastle United FC',
    home_goals: null,
    away_goals: null,
    result: null,
    home_odds: 1.80,
    draw_odds: 3.70,
    away_odds: 4.50,
    first_half_home_goals: null,
    first_half_away_goals: null,
    full_time_result: null,
    half_time_result: null,
    referee: null,
    home_shots: null,
    away_shots: null,
    home_shots_target: null,
    away_shots_target: null,
    home_fouls: null,
    away_fouls: null,
    home_corners: null,
    away_corners: null,
    home_yellows: null,
    away_yellows: null,
    home_reds: null,
    away_reds: null,
    created_at: '2026-05-01T00:00:00Z',
    status: 'TIMED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-8',
    season_id: '2025-26',
    date: '2026-05-31T14:00:00+01:00',
    home_team: 'Chelsea FC',
    away_team: 'Tottenham Hotspur FC',
    home_goals: null,
    away_goals: null,
    result: null,
    home_odds: 2.20,
    draw_odds: 3.40,
    away_odds: 3.30,
    first_half_home_goals: null,
    first_half_away_goals: null,
    full_time_result: null,
    half_time_result: null,
    referee: null,
    home_shots: null,
    away_shots: null,
    home_shots_target: null,
    away_shots_target: null,
    home_fouls: null,
    away_fouls: null,
    home_corners: null,
    away_corners: null,
    home_yellows: null,
    away_yellows: null,
    home_reds: null,
    away_reds: null,
    created_at: '2026-05-01T00:00:00Z',
    status: 'TIMED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-9',
    season_id: '2025-26',
    date: '2026-05-31T16:30:00+01:00',
    home_team: 'West Ham United FC',
    away_team: 'Everton FC',
    home_goals: null,
    away_goals: null,
    result: null,
    home_odds: 1.95,
    draw_odds: 3.60,
    away_odds: 4.20,
    first_half_home_goals: null,
    first_half_away_goals: null,
    full_time_result: null,
    half_time_result: null,
    referee: null,
    home_shots: null,
    away_shots: null,
    home_shots_target: null,
    away_shots_target: null,
    home_fouls: null,
    away_fouls: null,
    home_corners: null,
    away_corners: null,
    home_yellows: null,
    away_yellows: null,
    home_reds: null,
    away_reds: null,
    created_at: '2026-05-01T00:00:00Z',
    status: 'TIMED',
    minute: null,
    matchday: 35,
  },
  {
    id: 'demo-match-10',
    season_id: '2025-26',
    date: '2026-06-01T20:00:00+01:00',
    home_team: 'Brentford FC',
    away_team: 'Fulham FC',
    home_goals: null,
    away_goals: null,
    result: null,
    home_odds: 2.50,
    draw_odds: 3.30,
    away_odds: 2.90,
    first_half_home_goals: null,
    first_half_away_goals: null,
    full_time_result: null,
    half_time_result: null,
    referee: null,
    home_shots: null,
    away_shots: null,
    home_shots_target: null,
    away_shots_target: null,
    home_fouls: null,
    away_fouls: null,
    home_corners: null,
    away_corners: null,
    home_yellows: null,
    away_yellows: null,
    home_reds: null,
    away_reds: null,
    created_at: '2026-05-01T00:00:00Z',
    status: 'TIMED',
    minute: null,
    matchday: 35,
  },
];
