/**
 * Demo data for screenshot / preview mode.
 * Activated via `?demo=1`, `localStorage.kicker:demoMode === 'on'`, or `VITE_DEMO_MODE`.
 * Never shown when a Football-Data API key is configured for the real user.
 */

import type { Standing } from '../../types/index.js';

export const DEMO_STANDINGS: Standing[] = [
  {
    position: 1,
    team: { id: 1, name: 'Liverpool FC', shortName: 'Liverpool', tla: 'LIV', crest: '' },
    playedGames: 34,
    form: 'WWWDW',
    won: 24,
    draw: 6,
    lost: 4,
    points: 78,
    goalsFor: 82,
    goalsAgainst: 38,
    goalDifference: 44,
  },
  {
    position: 2,
    team: { id: 2, name: 'Arsenal FC', shortName: 'Arsenal', tla: 'ARS', crest: '' },
    playedGames: 34,
    form: 'WWDWW',
    won: 23,
    draw: 6,
    lost: 5,
    points: 75,
    goalsFor: 74,
    goalsAgainst: 35,
    goalDifference: 39,
  },
  {
    position: 3,
    team: { id: 3, name: 'Manchester City FC', shortName: 'Man City', tla: 'MCI', crest: '' },
    playedGames: 34,
    form: 'WDWWW',
    won: 22,
    draw: 7,
    lost: 5,
    points: 73,
    goalsFor: 79,
    goalsAgainst: 42,
    goalDifference: 37,
  },
  {
    position: 4,
    team: { id: 4, name: 'Newcastle United FC', shortName: 'Newcastle', tla: 'NEW', crest: '' },
    playedGames: 34,
    form: 'WDWLW',
    won: 20,
    draw: 5,
    lost: 9,
    points: 65,
    goalsFor: 67,
    goalsAgainst: 44,
    goalDifference: 23,
  },
  {
    position: 5,
    team: { id: 5, name: 'Tottenham Hotspur FC', shortName: 'Spurs', tla: 'TOT', crest: '' },
    playedGames: 34,
    form: 'DWWDL',
    won: 18,
    draw: 7,
    lost: 9,
    points: 61,
    goalsFor: 68,
    goalsAgainst: 55,
    goalDifference: 13,
  },
  {
    position: 6,
    team: { id: 6, name: 'Chelsea FC', shortName: 'Chelsea', tla: 'CHE', crest: '' },
    playedGames: 34,
    form: 'LWWWD',
    won: 17,
    draw: 8,
    lost: 9,
    points: 59,
    goalsFor: 63,
    goalsAgainst: 52,
    goalDifference: 11,
  },
  {
    position: 7,
    team: { id: 7, name: 'Aston Villa FC', shortName: 'Aston Villa', tla: 'AVL', crest: '' },
    playedGames: 34,
    form: 'WLDWW',
    won: 16,
    draw: 9,
    lost: 9,
    points: 57,
    goalsFor: 59,
    goalsAgainst: 49,
    goalDifference: 10,
  },
  {
    position: 8,
    team: { id: 8, name: 'Manchester United FC', shortName: 'Man United', tla: 'MUN', crest: '' },
    playedGames: 34,
    form: 'WWLDW',
    won: 15,
    draw: 7,
    lost: 12,
    points: 52,
    goalsFor: 53,
    goalsAgainst: 51,
    goalDifference: 2,
  },
  {
    position: 9,
    team: { id: 9, name: 'Brighton & Hove Albion FC', shortName: 'Brighton', tla: 'BHA', crest: '' },
    playedGames: 34,
    form: 'DWWLW',
    won: 14,
    draw: 9,
    lost: 11,
    points: 51,
    goalsFor: 61,
    goalsAgainst: 57,
    goalDifference: 4,
  },
  {
    position: 10,
    team: { id: 10, name: 'Nottingham Forest FC', shortName: 'Nott\'m Forest', tla: 'NFO', crest: '' },
    playedGames: 34,
    form: 'LDWDW',
    won: 14,
    draw: 7,
    lost: 13,
    points: 49,
    goalsFor: 48,
    goalsAgainst: 50,
    goalDifference: -2,
  },
  {
    position: 11,
    team: { id: 11, name: 'West Ham United FC', shortName: 'West Ham', tla: 'WHU', crest: '' },
    playedGames: 34,
    form: 'DWLDW',
    won: 12,
    draw: 10,
    lost: 12,
    points: 46,
    goalsFor: 50,
    goalsAgainst: 55,
    goalDifference: -5,
  },
  {
    position: 12,
    team: { id: 12, name: 'Brentford FC', shortName: 'Brentford', tla: 'BRE', crest: '' },
    playedGames: 34,
    form: 'WWLLD',
    won: 12,
    draw: 8,
    lost: 14,
    points: 44,
    goalsFor: 52,
    goalsAgainst: 57,
    goalDifference: -5,
  },
  {
    position: 13,
    team: { id: 13, name: 'Crystal Palace FC', shortName: 'Crystal Palace', tla: 'CRY', crest: '' },
    playedGames: 34,
    form: 'DLWLD',
    won: 11,
    draw: 10,
    lost: 13,
    points: 43,
    goalsFor: 44,
    goalsAgainst: 52,
    goalDifference: -8,
  },
  {
    position: 14,
    team: { id: 14, name: 'Fulham FC', shortName: 'Fulham', tla: 'FUL', crest: '' },
    playedGames: 34,
    form: 'WDDLW',
    won: 11,
    draw: 9,
    lost: 14,
    points: 42,
    goalsFor: 47,
    goalsAgainst: 54,
    goalDifference: -7,
  },
  {
    position: 15,
    team: { id: 15, name: 'AFC Bournemouth', shortName: 'Bournemouth', tla: 'BOU', crest: '' },
    playedGames: 34,
    form: 'LDDWL',
    won: 10,
    draw: 10,
    lost: 14,
    points: 40,
    goalsFor: 43,
    goalsAgainst: 56,
    goalDifference: -13,
  },
  {
    position: 16,
    team: { id: 16, name: 'Everton FC', shortName: 'Everton', tla: 'EVE', crest: '' },
    playedGames: 34,
    form: 'LLDWD',
    won: 8,
    draw: 11,
    lost: 15,
    points: 35,
    goalsFor: 37,
    goalsAgainst: 58,
    goalDifference: -21,
  },
  {
    position: 17,
    team: { id: 17, name: 'Wolverhampton Wanderers FC', shortName: 'Wolves', tla: 'WOL', crest: '' },
    playedGames: 34,
    form: 'LLLWD',
    won: 7,
    draw: 10,
    lost: 17,
    points: 31,
    goalsFor: 34,
    goalsAgainst: 63,
    goalDifference: -29,
  },
  {
    position: 18,
    team: { id: 18, name: 'Burnley FC', shortName: 'Burnley', tla: 'BUR', crest: '' },
    playedGames: 34,
    form: 'DLLLL',
    won: 6,
    draw: 8,
    lost: 20,
    points: 26,
    goalsFor: 32,
    goalsAgainst: 72,
    goalDifference: -40,
  },
  {
    position: 19,
    team: { id: 19, name: 'Sheffield United FC', shortName: 'Sheffield Utd', tla: 'SHU', crest: '' },
    playedGames: 34,
    form: 'LLLLD',
    won: 5,
    draw: 7,
    lost: 22,
    points: 22,
    goalsFor: 29,
    goalsAgainst: 79,
    goalDifference: -50,
  },
  {
    position: 20,
    team: { id: 20, name: 'Luton Town FC', shortName: 'Luton', tla: 'LUT', crest: '' },
    playedGames: 34,
    form: 'LLLLL',
    won: 4,
    draw: 6,
    lost: 24,
    points: 18,
    goalsFor: 26,
    goalsAgainst: 84,
    goalDifference: -58,
  },
];
