/**
 * Demo data for screenshot / preview mode.
 * Activated via `?demo=1`, `localStorage.kicker:demoMode === 'on'`, or `VITE_DEMO_MODE`.
 * Never shown when a Football-Data API key is configured for the real user.
 */

import type { StoredPrediction } from '../../services/predictionTracker.js';

export const DEMO_PREDICTIONS: StoredPrediction[] = [
  // ── Match 1: Man City 3-1 Aston Villa (FINISHED) — correct prediction ─────
  {
    id: 'demo-pred-1',
    matchId: 'demo-match-1',
    homeTeam: 'Manchester City FC',
    awayTeam: 'Aston Villa FC',
    predictedResult: 'H',
    predictedHomeGoals: 2,
    predictedAwayGoals: 1,
    confidence: 74,
    actualResult: 'H',
    actualHomeGoals: 3,
    actualAwayGoals: 1,
    isCorrect: true,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-23T15:00:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WWWDW',
    awayForm: 'WLDWW',
    keyFactors: [
      'Home side undefeated in last 6 at the Etihad',
      'Away side missing key attacking midfielder through suspension',
      'Head-to-head record heavily favours the home side at this venue',
    ],
    poissonProbs: { homeWin: 0.56, draw: 0.24, awayWin: 0.20 },
  },

  // ── Match 2: Liverpool 2-2 Tottenham (FINISHED) — wrong prediction (predicted H) ──
  {
    id: 'demo-pred-2',
    matchId: 'demo-match-2',
    homeTeam: 'Liverpool FC',
    awayTeam: 'Tottenham Hotspur FC',
    predictedResult: 'H',
    predictedHomeGoals: 2,
    predictedAwayGoals: 0,
    confidence: 62,
    actualResult: 'D',
    actualHomeGoals: 2,
    actualAwayGoals: 2,
    isCorrect: false,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-23T15:00:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WWWDW',
    awayForm: 'DWWDL',
    keyFactors: [
      'Home side have the league\'s best defensive record at Anfield this season',
      'Away side in strong road form with 4 wins in last 6 away fixtures',
      'Both sides average over 1.8 goals per game in recent outings',
    ],
    poissonProbs: { homeWin: 0.48, draw: 0.28, awayWin: 0.24 },
  },

  // ── Match 3: Arsenal 1-0 Chelsea (FINISHED) — correct prediction ──────────
  {
    id: 'demo-pred-3',
    matchId: 'demo-match-3',
    homeTeam: 'Arsenal FC',
    awayTeam: 'Chelsea FC',
    predictedResult: 'H',
    predictedHomeGoals: 1,
    predictedAwayGoals: 0,
    confidence: 58,
    actualResult: 'H',
    actualHomeGoals: 1,
    actualAwayGoals: 0,
    isCorrect: true,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-23T17:30:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WWDWW',
    awayForm: 'LWWWD',
    keyFactors: [
      'Arsenal have kept clean sheets in 4 of their last 5 home matches',
      'Chelsea yet to win away against a top-four side this season',
      'ELO differential of 48 points favours the home side',
    ],
    poissonProbs: { homeWin: 0.44, draw: 0.31, awayWin: 0.25 },
  },

  // ── Match 4: Nott'm Forest 0-2 Man United (FINISHED) — correct prediction ─
  {
    id: 'demo-pred-4',
    matchId: 'demo-match-4',
    homeTeam: 'Nottingham Forest FC',
    awayTeam: 'Manchester United FC',
    predictedResult: 'A',
    predictedHomeGoals: 0,
    predictedAwayGoals: 2,
    confidence: 55,
    actualResult: 'A',
    actualHomeGoals: 0,
    actualAwayGoals: 2,
    isCorrect: true,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-23T17:30:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'LDWDW',
    awayForm: 'WWLDW',
    keyFactors: [
      'Away side have won 3 of their last 4 matches on the road',
      'Home side scoring fewer than 1 goal per game over past month',
      'Poisson model gives away side slight edge on current scoring rates',
    ],
    poissonProbs: { homeWin: 0.30, draw: 0.32, awayWin: 0.38 },
  },

  // ── Match 5: Newcastle v Brighton (IN_PLAY) — no actuals yet ─────────────
  {
    id: 'demo-pred-5',
    matchId: 'demo-match-5',
    homeTeam: 'Newcastle United FC',
    awayTeam: 'Brighton & Hove Albion FC',
    predictedResult: 'H',
    predictedHomeGoals: 2,
    predictedAwayGoals: 1,
    confidence: 57,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-24T15:00:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WDWLW',
    awayForm: 'DWWLW',
    keyFactors: [
      'Home side undefeated in their last 4 at St. James\' Park',
      'Away side\'s pressing game tends to create chances against deeper blocks',
      'Form over the last 8 matches gives a marginal edge to the home side',
    ],
    poissonProbs: { homeWin: 0.44, draw: 0.29, awayWin: 0.27 },
  },

  // ── Match 6: Man City v Liverpool (upcoming) ──────────────────────────────
  {
    id: 'demo-pred-6',
    matchId: 'demo-match-6',
    homeTeam: 'Manchester City FC',
    awayTeam: 'Liverpool FC',
    predictedResult: 'D',
    predictedHomeGoals: 1,
    predictedAwayGoals: 1,
    confidence: 61,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-30T15:00:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WDWWW',
    awayForm: 'WWWDW',
    keyFactors: [
      'Last 5 meetings between these sides produced 3 draws and 2 one-goal margins',
      'Both squads near full fitness with no significant absences reported',
      'High-stakes encounter — both sides have incentive to avoid defeat',
    ],
    poissonProbs: { homeWin: 0.36, draw: 0.30, awayWin: 0.34 },
  },

  // ── Match 7: Arsenal v Newcastle (upcoming) ───────────────────────────────
  {
    id: 'demo-pred-7',
    matchId: 'demo-match-7',
    homeTeam: 'Arsenal FC',
    awayTeam: 'Newcastle United FC',
    predictedResult: 'H',
    predictedHomeGoals: 2,
    predictedAwayGoals: 0,
    confidence: 67,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-30T17:30:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WWDWW',
    awayForm: 'WDWLW',
    keyFactors: [
      'Arsenal have the second-best home record in the division this season',
      'Away side conceded first in 7 of last 10 away fixtures',
      'Poisson model projects a 67% probability of the home side scoring first',
    ],
    poissonProbs: { homeWin: 0.50, draw: 0.27, awayWin: 0.23 },
  },

  // ── Match 8: Chelsea v Tottenham (upcoming) ───────────────────────────────
  {
    id: 'demo-pred-8',
    matchId: 'demo-match-8',
    homeTeam: 'Chelsea FC',
    awayTeam: 'Tottenham Hotspur FC',
    predictedResult: 'H',
    predictedHomeGoals: 2,
    predictedAwayGoals: 1,
    confidence: 56,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-31T14:00:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'LWWWD',
    awayForm: 'DWWDL',
    keyFactors: [
      'Derby fixtures at Stamford Bridge have averaged 3.1 goals over the past 5 seasons',
      'Home side\'s attacking output improved significantly since tactical shift in February',
      'Away side\'s defensive record away from home is the weakest in the top eight',
    ],
    poissonProbs: { homeWin: 0.42, draw: 0.30, awayWin: 0.28 },
  },

  // ── Match 9: West Ham v Everton (upcoming) ────────────────────────────────
  {
    id: 'demo-pred-9',
    matchId: 'demo-match-9',
    homeTeam: 'West Ham United FC',
    awayTeam: 'Everton FC',
    predictedResult: 'H',
    predictedHomeGoals: 2,
    predictedAwayGoals: 0,
    confidence: 69,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-05-31T16:30:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'DWLDW',
    awayForm: 'LLDWD',
    keyFactors: [
      'Away side without a win in their last 7 fixtures in all competitions',
      'Home side have scored in each of their last 9 home matches',
      'ELO and form models in agreement — home win probability above 55%',
    ],
    poissonProbs: { homeWin: 0.55, draw: 0.27, awayWin: 0.18 },
  },

  // ── Match 10: Brentford v Fulham (upcoming) ───────────────────────────────
  {
    id: 'demo-pred-10',
    matchId: 'demo-match-10',
    homeTeam: 'Brentford FC',
    awayTeam: 'Fulham FC',
    predictedResult: 'D',
    predictedHomeGoals: 1,
    predictedAwayGoals: 1,
    confidence: 58,
    timestamp: '2026-05-22T10:00:00Z',
    matchDate: '2026-06-01T20:00:00+01:00',
    matchday: 35,
    modelVersion: 'v3.5-MVP',
    homeForm: 'WWLLD',
    awayForm: 'WDDLW',
    keyFactors: [
      'West London derby — last 4 meetings finished level or within one goal',
      'Both sides inconsistent in recent weeks with 2 wins and 2 losses each',
      'Head-to-head model gives neither side a meaningful advantage at this venue',
    ],
    poissonProbs: { homeWin: 0.36, draw: 0.33, awayWin: 0.31 },
  },
];
